stages:
  download_data:
    cmd: python src\data\download_data.py params.yaml
    deps:
    - src\data\download_data.py
    params:
    - input_url_data
    - output_raw_data
  split_data:
    cmd: python src\data\split_data.py params.yaml
    deps:
    - src\data\split_data.py
    params:
    - feature_params.features_to_drop
    - feature_params.target
    - output_raw_data
    - splitting_params
  make_dataset:
    cmd: python src\data\make_dataset.py params.yaml
    deps:
    - src\data\make_dataset.py
    params:
    - splitting_params.X_train_path
    - splitting_params.X_test_path
    - feature_transforming
