input_url_data: "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
output_raw_data: "data/raw/titanic_downloaded_data.csv"
splitting_params:
  random_state: 17
  test_size: 0.3
  stratify: false
  X_train_path: 'data/raw/X_train.csv'
  X_test_path: 'data/raw/X_test.csv'
  y_train_path: 'data/processed/y_train.csv'
  y_test_path: 'data/processed/y_test.csv'
feature_transforming:
  X_train_transformed_path: "data/processed/X_train_transformed.csv"
  X_test_transformed_path: "data/processed/X_test_transformed.csv"
  transformer_path: "models/transformer.pkl"
feature_params:
  categorical_features:
    - "Pclass"
    - "Sex"
    - "SibSp"
    - "Parch"
    - "Embarked"
  numerical_features:
    - "Age"
    - "Fare"
  features_to_drop:
    - "PassengerId"
    - "Name"
    - "Ticket"
    - "Cabin"
  target: "Survived"